{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rnaturalearth
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rnaturalearth_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rnaturalearth/rnaturalearth_{{ version }}.tar.gz
  sha256: 36aa5f8d23a7854c221d9f49a753d79fe7c001c83ddf0fcb888477cc7fa287af

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-httr >=1.1.0
    - r-jsonlite
    - r-sf >=0.3_4
    - r-terra
  run:
    - r-base
    - r-cli
    - r-httr >=1.1.0
    - r-jsonlite
    - r-sf >=0.3_4
    - r-terra

test:
  commands:
    - $R -e "library('rnaturalearth')"           # [not win]
    - "\"%R%\" -e \"library('rnaturalearth')\""  # [win]

about:
  home: https://github.com/ropenscilabs/rnaturalearth
  license: MIT
  summary: Facilitates mapping by making natural earth map data from <http://www.naturalearthdata.com/> more easily available to R users.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
