{% set version = "0.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rnaturalearth
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rnaturalearth_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rnaturalearth/rnaturalearth_{{ version }}.tar.gz
  sha256: d5c857aade34c93be72c7d486b0545c77d305f4bff085382e93acfcb2e345132

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-httr >=1.1.0
    - r-jsonlite
    - r-sf >=0.3_4
    - r-sp >=1.0.15
    - r-terra
  run:
    - r-base
    - r-httr >=1.1.0
    - r-jsonlite
    - r-sf >=0.3_4
    - r-sp >=1.0.15
    - r-terra

test:
  commands:
    - $R -e "library('rnaturalearth')"           # [not win]
    - "\"%R%\" -e \"library('rnaturalearth')\""  # [win]

about:
  home: https://github.com/ropenscilabs/rnaturalearth
  license: MIT
  summary: Facilitates mapping by making natural earth map data from <http://www.naturalearthdata.com/> more easily available to R users.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
